import { useState, useEffect } from "react";
import axios from "axios";
import { format } from "date-fns";
import { Bot, History as HistoryIcon, Loader2 } from "lucide-react";
import Markdown from "react-markdown";
import rehypeHighlight from "rehype-highlight";
import "highlight.js/styles/atom-one-dark.css";

export default function History() {
  const [reviews, setReviews] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchHistory = async () => {
      try {
        const res = await axios.get(`${import.meta.env.VITE_API_URL}/reviews`);
        setReviews(res.data.data);
      } catch (err) {
        console.error("Error fetching history");
      } finally {
        setLoading(false);
      }
    };
    fetchHistory();
  }, []);

  return (
    <div className="flex-1 p-4 sm:p-6 md:p-10 max-w-[1400px] w-full mx-auto">
      <div className="flex items-center gap-3 mb-6 sm:mb-8">
        <div className="bg-emerald-500/20 p-2.5 sm:p-3 rounded-2xl border border-emerald-500/30">
          <HistoryIcon className="w-6 h-6 sm:w-7 sm:h-7 text-emerald-400" />
        </div>
        <div>
          <h2 className="text-xl sm:text-2xl font-bold bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-transparent">Review History</h2>
          <p className="text-xs sm:text-sm text-slate-400">Past code analyses generated by AI.</p>
        </div>
      </div>

      {loading ? (
        <div className="flex items-center justify-center p-20">
          <Loader2 className="w-10 h-10 text-emerald-400 animate-spin" />
        </div>
      ) : reviews.length === 0 ? (
        <div className="bg-slate-900/50 border border-slate-800 rounded-3xl p-10 sm:p-16 text-center shadow-2xl backdrop-blur-xl">
          <Bot className="w-12 h-12 sm:w-16 sm:h-16 text-slate-600 mx-auto mb-4 opacity-50" />
          <h3 className="text-lg sm:text-xl text-slate-300 font-medium">No History Found</h3>
          <p className="text-sm sm:text-base text-slate-500 mt-2">You haven't reviewed any code yet.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-8">
          {reviews.map((review) => (
            <div key={review._id} className="bg-slate-900/50 border border-slate-800 rounded-3xl shadow-xl backdrop-blur-xl overflow-hidden flex flex-col">
              <div className="bg-slate-800/50 px-6 py-4 flex items-center justify-between border-b border-slate-800/80">
                 <div className="flex items-center gap-3">
                   <div className="px-2.5 py-1 rounded-md bg-indigo-500/20 border border-indigo-500/30 text-indigo-300 text-xs font-mono uppercase tracking-wider">
                     {review.language}
                   </div>
                   <span className="text-slate-400 text-sm">
                     {format(new Date(review.createdAt), "MMM d, yyyy • h:mm a")}
                   </span>
                 </div>
              </div>
              <div className="p-6 grid grid-cols-1 md:grid-cols-2 gap-6 items-start">
                <div className="bg-[#0f172a] rounded-2xl p-5 border border-slate-800 h-full max-h-[500px] overflow-auto">
                   <h4 className="text-xs uppercase font-bold text-slate-500 mb-3 tracking-wider">Original Code</h4>
                   <pre className="text-sm text-slate-300 font-mono"><code>{review.code}</code></pre>
                </div>
                <div className="bg-[#0B1120] rounded-2xl p-5 border border-slate-800 h-full max-h-[500px] overflow-auto prose prose-invert prose-indigo max-w-none text-slate-300">
                   <h4 className="text-xs uppercase font-bold text-slate-500 mb-3 tracking-wider flex items-center gap-2">
                     <Bot className="w-4 h-4 text-indigo-400" /> AI Feedback
                   </h4>
                   <Markdown
                    rehypePlugins={[rehypeHighlight]}
                    components={{
                      code({ node, inline, className, children, ...props }) {
                        const match = /language-(\w+)/.exec(className || "");
                        return !inline && match ? (
                          <div className="rounded-xl overflow-hidden my-4 border border-slate-800 shadow-lg bg-[#0E1526]">
                            <code className={className} {...props}>{children}</code>
                          </div>
                        ) : (
                          <code {...props} className="bg-slate-800/60 text-indigo-300 px-1.5 py-0.5 rounded-md text-sm font-mono border border-slate-700/50">{children}</code>
                        );
                      },
                      pre({ children }) {
                        return <pre className="!bg-transparent !p-0 !m-0 overflow-x-auto">{children}</pre>;
                      }
                    }}
                   >
                     {review.aiResponse}
                   </Markdown>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
